[package]
name = "learn-opengl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
gl = "0.14.0" # OpenGL bindings
glfw = "0.51.0" # Window: C++ GLFW wrapper
nalgebra = "0.32.1" # Linear algebra
bytemuck = "1.13.0" # bit cast
image = "0.24.5" # image processing
