[package]
name = "learn-opengl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
bytemuck = "1.13.0" # bit cast
gl33 = "0.2.1" # OpenGL 3.3
beryllium = "0.9.0" # WM: wrappers for fermium SDL2 bindings
image = "0.24.5" # image processing
nalgebra = "0.32.1" # Linear algebra
