name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-miri-${{ hashFiles('**/Cargo.toml') }}
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --release --all-features --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose --all-targets
      
  lint:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-miri-${{ hashFiles('**/Cargo.toml') }}
    - uses: dtolnay/rust-toolchain@stable
    - name: Fmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
