name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_TOOLCHAIN: nightly

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
    - name: install libxrandr
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libxrandr-dev
    - name: Build
      run: cargo build --release --all-features --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose --all-targets
